# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

net_seq_classification_fit <- function(net, x, y, batch_size, epochs, optimizer, verbose) {
    .Call('tinydnn_net_seq_classification_fit', PACKAGE = 'tinydnn', net, x, y, batch_size, epochs, optimizer, verbose)
}

net_seq_classification_predict <- function(net, x) {
    .Call('tinydnn_net_seq_classification_predict', PACKAGE = 'tinydnn', net, x)
}

net_seq_constructor <- function(name) {
    .Call('tinydnn_net_seq_constructor', PACKAGE = 'tinydnn', name)
}

net_seq_name <- function(net) {
    .Call('tinydnn_net_seq_name', PACKAGE = 'tinydnn', net)
}

net_seq_layer_size <- function(net) {
    .Call('tinydnn_net_seq_layer_size', PACKAGE = 'tinydnn', net)
}

net_seq_out_data_size <- function(net) {
    .Call('tinydnn_net_seq_out_data_size', PACKAGE = 'tinydnn', net)
}

net_seq_in_data_size <- function(net) {
    .Call('tinydnn_net_seq_in_data_size', PACKAGE = 'tinydnn', net)
}

net_seq_add_layer <- function(net, layer) {
    .Call('tinydnn_net_seq_add_layer', PACKAGE = 'tinydnn', net, layer)
}

net_seq_regression_fit <- function(net, x, y, batch_size, epochs, optimizer, verbose) {
    .Call('tinydnn_net_seq_regression_fit', PACKAGE = 'tinydnn', net, x, y, batch_size, epochs, optimizer, verbose)
}

net_seq_regression_predict <- function(net, x) {
    .Call('tinydnn_net_seq_regression_predict', PACKAGE = 'tinydnn', net, x)
}

